spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lectureEvaluation2
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Thymeleaf 설정
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML

  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        org:
          hibernate:
            SQL: DEBUG
            type:
              descriptor:
                sql:
                  BasicBinder: TRACE
        show_sql: true
    defer-datasource-initialization: true